### ISSUE TITLE
[bug] Could not pass event InventoryClickEvent to Storage v2.3

### ISSUE THREAD

**Issue by makegodhere** [VoChiDanh/Storage#21]
only console error

```
[10:02:08 ERROR]: Could not pass event InventoryClickEvent to Storage v2.3
java.lang.NullPointerException: null
	at java.base/java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
	at Storage.jar/net.danh.storage.Action.Deposit.doAction(Deposit.java:102) ~[Storage.jar:?]
	at Storage.jar/net.danh.storage.GUI.ItemStorage.lambda$getInventory$3(ItemStorage.java:191) ~[Storage.jar:?]
	at Storage.jar/net.danh.storage.GUI.manager.InteractiveItem.handleClick(InteractiveItem.java:202) ~[Storage.jar:?]
	at Storage.jar/net.danh.storage.GUI.listeners.GUIClickListener.onInventoryClick(GUIClickListener.java:41) ~[Storage.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1406.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3332) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:154) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1624) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:207) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:128) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1601) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1594) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:117) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1744) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1370) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:344) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by VoChiDanh** [comment]
Forgot to say, check the file in https://github.com/VoChiDanh/Storage/blob/master/src%2Fmain%2Fresources%2Fmessage.yml

And add line 27 to your file message
